// Code generated by goctl. DO NOT EDIT.
// Source: add.proto

package server

import (
	"context"

	"example.com/m/v2/rpc/add"
	"example.com/m/v2/rpc/internal/logic"
	"example.com/m/v2/rpc/internal/svc"
)

type AdderServer struct {
	svcCtx *svc.ServiceContext
	add.UnimplementedAdderServer
}

func NewAdderServer(svcCtx *svc.ServiceContext) *AdderServer {
	return &AdderServer{
		svcCtx: svcCtx,
	}
}

func (s *AdderServer) GetTodoList(ctx context.Context, in *add.AddReq) (*add.AddResp, error) {
	l := logic.NewGetTodoListLogic(ctx, s.svcCtx)
	return l.GetTodoList(in)
}
