// Code generated by goctl. DO NOT EDIT.
// Source: todoList.proto

package server

import (
	"context"

	"example.com/m/v2/todoList/internal/logic"
	"example.com/m/v2/todoList/internal/svc"
	"example.com/m/v2/todoList/todoList"
)

type AdderServer struct {
	svcCtx *svc.ServiceContext
	todoList.UnimplementedAdderServer
}

func NewAdderServer(svcCtx *svc.ServiceContext) *AdderServer {
	return &AdderServer{
		svcCtx: svcCtx,
	}
}

func (s *AdderServer) GetTodoList(ctx context.Context, in *todoList.GetTodoListReq) (*todoList.GetTodoListResp, error) {
	l := logic.NewGetTodoListLogic(ctx, s.svcCtx)
	return l.GetTodoList(in)
}

func (s *AdderServer) SearchTodoList(ctx context.Context, in *todoList.SearchTodoListReq) (*todoList.SearchTodoListResp, error) {
	l := logic.NewSearchTodoListLogic(ctx, s.svcCtx)
	return l.SearchTodoList(in)
}

func (s *AdderServer) SaveTodoList(ctx context.Context, in *todoList.SaveTodoListReq) (*todoList.SaveTodoListResp, error) {
	l := logic.NewSaveTodoListLogic(ctx, s.svcCtx)
	return l.SaveTodoList(in)
}
