// Code generated by goctl. DO NOT EDIT.
package types

type AddReq struct {
	AccountID int64   `form:"account_id"`
	Months    []int64 `form:"months"`
}

type AddResp struct {
	Ok bool `json:"ok"`
}

type CheckReq struct {
	Book string `form:"book"`
}

type CheckResp struct {
	Found bool  `json:"found"`
	Price int64 `json:"price"`
}
