// Code generated by goctl. DO NOT EDIT.
package types

type GetTodoListReq struct {
	AccountID int64   `form:"account_id"`
	Months    []int64 `form:"months"`
}

type GetTodoListResp struct {
	TodoList []*TodoList `json:"todoList"`
	Ok       bool        `json:"ok"`
}

type SearchTodoListReq struct {
	AccountID int64  `form:"account_id"`
	Keyword   string `form:"keyword"`
}

type SearchTodoListResp struct {
	TodoList []*TodoList `json:"todoList"`
	Ok       bool        `json:"ok"`
}

type TodoList struct {
	Id        int64  `json:"id"`        // 主键 id
	AccountId int64  `json:"accountId"` // 账户 id
	Time      int64  `json:"time"`      // 日程时间
	Month     int64  `json:"month"`     // 月份
	Extra     string `json:"extra"`     // 日程详细信息
	Status    int64  `json:"status"`    // 状态 0:未完成 1:已完成
}

type SaveTodoListReq struct {
	Time  int64  `form:"time"`
	Extra string `form:"extra"`
}

type SaveTodoListResp struct {
	Ok bool `json:"ok"`
}
