// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"example.com/m/v2/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getTodoList",
				Handler: GetTodoListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/saveTodoList",
				Handler: SaveTodoListHandler(serverCtx),
			},
		},
	)
}
