// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: todoList.proto

package todoList

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTodoListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID int64   `protobuf:"varint,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Months    []int64 `protobuf:"varint,2,rep,packed,name=months,proto3" json:"months,omitempty"`
}

func (x *GetTodoListReq) Reset() {
	*x = GetTodoListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoList_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTodoListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoListReq) ProtoMessage() {}

func (x *GetTodoListReq) ProtoReflect() protoreflect.Message {
	mi := &file_todoList_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoListReq.ProtoReflect.Descriptor instead.
func (*GetTodoListReq) Descriptor() ([]byte, []int) {
	return file_todoList_proto_rawDescGZIP(), []int{0}
}

func (x *GetTodoListReq) GetAccountID() int64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *GetTodoListReq) GetMonths() []int64 {
	if x != nil {
		return x.Months
	}
	return nil
}

type GetTodoListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool        `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	TodoList []*TodoList `protobuf:"bytes,2,rep,name=todoList,proto3" json:"todoList,omitempty"`
}

func (x *GetTodoListResp) Reset() {
	*x = GetTodoListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoList_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTodoListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoListResp) ProtoMessage() {}

func (x *GetTodoListResp) ProtoReflect() protoreflect.Message {
	mi := &file_todoList_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoListResp.ProtoReflect.Descriptor instead.
func (*GetTodoListResp) Descriptor() ([]byte, []int) {
	return file_todoList_proto_rawDescGZIP(), []int{1}
}

func (x *GetTodoListResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetTodoListResp) GetTodoList() []*TodoList {
	if x != nil {
		return x.TodoList
	}
	return nil
}

type TodoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	AccountId int64  `protobuf:"varint,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	Time      int64  `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	Month     int64  `protobuf:"varint,4,opt,name=Month,proto3" json:"Month,omitempty"`
	Extra     string `protobuf:"bytes,5,opt,name=Extra,proto3" json:"Extra,omitempty"`
	Status    int64  `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *TodoList) Reset() {
	*x = TodoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoList_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoList) ProtoMessage() {}

func (x *TodoList) ProtoReflect() protoreflect.Message {
	mi := &file_todoList_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoList.ProtoReflect.Descriptor instead.
func (*TodoList) Descriptor() ([]byte, []int) {
	return file_todoList_proto_rawDescGZIP(), []int{2}
}

func (x *TodoList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TodoList) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *TodoList) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *TodoList) GetMonth() int64 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *TodoList) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *TodoList) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_todoList_proto protoreflect.FileDescriptor

var file_todoList_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x74, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x0e, 0x67, 0x65,
	0x74, 0x54, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f,
	0x6e, 0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x6f, 0x6e, 0x74,
	0x68, 0x73, 0x22, 0x51, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x2e, 0x0a, 0x08, 0x74, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x08, 0x74, 0x6f, 0x64,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x90, 0x01, 0x0a, 0x08, 0x54, 0x6f, 0x64, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x4b, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x65,
	0x72, 0x12, 0x42, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x18, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x67, 0x65, 0x74, 0x54,
	0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x74, 0x6f, 0x64,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x67, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_todoList_proto_rawDescOnce sync.Once
	file_todoList_proto_rawDescData = file_todoList_proto_rawDesc
)

func file_todoList_proto_rawDescGZIP() []byte {
	file_todoList_proto_rawDescOnce.Do(func() {
		file_todoList_proto_rawDescData = protoimpl.X.CompressGZIP(file_todoList_proto_rawDescData)
	})
	return file_todoList_proto_rawDescData
}

var file_todoList_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_todoList_proto_goTypes = []interface{}{
	(*GetTodoListReq)(nil),  // 0: todoList.getTodoListReq
	(*GetTodoListResp)(nil), // 1: todoList.getTodoListResp
	(*TodoList)(nil),        // 2: todoList.TodoList
}
var file_todoList_proto_depIdxs = []int32{
	2, // 0: todoList.getTodoListResp.todoList:type_name -> todoList.TodoList
	0, // 1: todoList.adder.getTodoList:input_type -> todoList.getTodoListReq
	1, // 2: todoList.adder.getTodoList:output_type -> todoList.getTodoListResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_todoList_proto_init() }
func file_todoList_proto_init() {
	if File_todoList_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_todoList_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTodoListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoList_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTodoListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoList_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_todoList_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todoList_proto_goTypes,
		DependencyIndexes: file_todoList_proto_depIdxs,
		MessageInfos:      file_todoList_proto_msgTypes,
	}.Build()
	File_todoList_proto = out.File
	file_todoList_proto_rawDesc = nil
	file_todoList_proto_goTypes = nil
	file_todoList_proto_depIdxs = nil
}
